redis:
    host: localhost
    port: 6379
    db: 0

analytics:
    host: localhost
    port: 9999
    realm: serpent
    auth:
        username: backend
        password: "12345"
    topic: ISAAC

frame_handlers:
    COLLECT_FRAMES_FOR_CONTEXT:
        context: game
        interval: 1

input_recorder:
    redis_key: SERPENT:INPUTS

frame_grabber:
    redis_key: SERPENT:FRAMES

visual_debugger:
    redis_key_prefix: SERPENT:VISUAL_DEBUGGER
    available_buckets:
        - "0"
        - "1"
        - "2"
        - "3"